// eslint-disable-next-line @typescript-eslint/ban-ts-comment
import type {NextPage} from "next";
import Head from "next/head";
import {trpc} from "../utils/trpc";
import TechnologyCard from "../components/TechnologyCard";
import BedGrid from "../components/bedgrid";
import sunbed from "/src/images/sunbeds.jpg";

import Sunbed from "../components/Sunbed";
import SunbedBooked from "../components/SunbedBooked";
import {useState} from "react";
import {signIn, signOut, useSession} from "next-auth/react";
import Image from "next/image";
type TechnologyCardProps = {
    name: string;
    description: string;
    documentation: string;
};
const divStyle={
    overflowY: 'scroll',
    border:'1px solid red',
    width:'500px',
    float: 'left',
    height:'500px',
    position:'relative'
};
const Home: NextPage = () => {
    const hello = trpc.useQuery(["example.hello", {text: "from tRPC"}]);
    const grid = trpc.useQuery(["example.grid", {text: "from tRPC"}]);

    const multi = [[ false,  false, false, true, true, false, true, false, false, true, false,, false, true, false,, false, true, false,], [ false, true, false, true,  true, false, true, true, false, true, true,], [false, true, false, true, true, true,  true, true, true, true, true,], [ true, true,  true, true, true, true, true, true, false, true, false]]


    const { data: session, status } = useSession();
    // @ts-ignore
    return (
        <>
            <Head>
                <title>Book</title>
                <meta name="description" content="Generated by create-t3-app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>


            <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
                {session ? (
                    <div>
                    <div className="pt-6 text-1xl text-blue-500 flex justify-center items-center w-full">
                        <h3>Welcome {session.user?.name}</h3>

                    </div>
<div className="pt-6 text-1xl text-blue-500 flex justify-center items-center w-full">
                        <button onClick={() => signOut()}>
                            Logout
                        </button>
</div>
                    </div>
                ) : (
                    <div >
                        <div className="pt-6 text-1xl text-blue-500 flex justify-center items-center w-full">
                            <button onClick={() => signIn("discord")}>
                                Login with Discord
                            </button>
                        </div>
                        <div className="pt-6 text-1xl text-blue-500 flex justify-center items-center w-full">
                            <button onClick={() => signIn("google")}>
                                Login with Google
                            </button>
                        </div>
                    </div>
                )}

                <div className="pt-6 text-2xl text-blue-500 flex justify-center items-center w-full">

                    <p>Book a SunBed</p>
                </div>

                <div className="pt-6 text-1xl text-black-400 flex justify-center items-center w-full">

                    {/*{grid.data ? <p>{grid.data.greeting}</p> : <p>Loading..</p>}*/}

                </div >
                {/*<Image*/}
                {/*    src={sunbedimg}*/}
                {/*    alt="Picture of the author"*/}
                {/*    width={500}*/}
                {/*    height={500}*/}
                {/*/>*/}

                {/*const [cartItems, setCartItems] = useState(40);*/}
                {multi.map((bed) => {
                    return (<div style={{whiteSpace:'nowrap',justifyContent:'flex-start',flexDirection:'row',overflow : 'scroll',minHeight:'100px',height:'5vw'}}>{bed.map((x) => {

                            if(x){

                                return (<SunbedBooked ></SunbedBooked>)
                            }
                            return (<Sunbed ></Sunbed>)
                        })}</div>);
                    }
                )}

                <div className="grid gap-2 pt-2 mt-2 text-center md:grid-cols-2 lg:w-2/3">
                <TechnologyCard
                    name="Book Sunbeds"
                    description=""
                    documentation="/book"
                />
                <TechnologyCard
                    name="Back to Home"
                    description=""
                    documentation="/"
                />
                </div>
            </main>


        </>
    );
};

export default Home;
