import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import  TechnologyCard  from "../components/TechnologyCard";
import link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";


type TechnologyCardProps = {
  name: string;
  description: string;
  documentation: string;
};

const Home: NextPage = () => {
  const { data: session, status } = useSession();
  // @ts-ignore
  return (
    <>

      <Head>
        <title>Krevataki</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="manifest" href="/manifest.json" />
        <link rel="apple-touch-icon" href="/icon.png"></link>
        <meta name="theme-color" content="#fff" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">

        <h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700">
          Kre<span className="text-purple-300">va</span>taki
        </h1>
        <div className="grid gap-3 pt-3 mt-3 text-center md:grid-cols-1 lg:w-2/3">


          <TechnologyCard
            name="About"
            description=""
            documentation="/about"
          />

        </div>
          <div className="grid gap-3 pt-3 mt-3 text-center md:grid-cols-1 lg:w-2/3">
          <TechnologyCard
              name="Go to App"
              description="Book a Sunbed in seconds"
              documentation="/book"
          />
          </div>
        {session ? (
            <div>
              <p>hi {session.user?.name}</p>

              <button onClick={() => signOut()}>
                Logout
              </button>
            </div>
        ) : (
          <div>
            <div>
              <button onClick={() => signIn("discord")}>
                Login with Discord
              </button>
            </div>
            <div>
              <button onClick={() => signIn("google")}>
                Login with Google
              </button>
            </div>
          </div>
        )}

      </main>
    </>
  );
};

export default Home;
